name: Bug Report
description: File a bug report for Shell Integration Problems
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: command-results
      attributes:
          label: Extension Logs
          description: Please paste the console logs from the Debug Console.
          render: shell
      validations:
          required: true
    - type: textarea
      id: additional-information
      attributes:
          label: Additional Information
          description: Add any other details about the problem here.
