name: Bug Report
description: File a bug report for Shell Integration Problems
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: commands-run
      attributes:
          label: Commands Run
          description: What command(s) did you run using the extension?
          placeholder: |
              e.g., 
              1. shell-integration-problems.runInNewTerminal
              Command: echo "Hello, World!"
              2. shell-integration-problems.runInLastUsedTerminal
              Command: ls -la
      validations:
          required: true
    - type: textarea
      id: command-results
      attributes:
          label: Command Results
          description: Please paste the console logs from the extension.ts file for the commands you ran.
          placeholder: |
              e.g.,
              Waiting for shell integration...
              Shell integration available
              { execution: ... }
              { chunk: ... }
              Shell execution started in terminal: shell-integration-problems
              Shell execution ended in terminal: shell-integration-problems echo "Hello, World!" 0
              Exit code: 0
          render: shell
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: Add any other context about the problem here.
