name: Report Shell Integration Problem
description: File a report for Shell Integration problems
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this report!
    - type: textarea
      id: debug-console-logs
      attributes:
          label: Debug Console Logs
          description: Please paste the console logs from the Debug Console.
          render: shell
      validations:
          required: true
    - type: textarea
      id: additional-information
      attributes:
          label: Additional Information
          description: Add any other details about the problems here.
