name: Report Shell Integration Problem
description: Use this template to report problems with VSCode's Terminal Shell Integration API.
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this report!
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Provide a clear description of the problem you're experiencing.
      validations:
          required: true
    - type: textarea
      id: debug-console-logs
      attributes:
          label: Debug Console Logs
          description: Please paste the console logs from the Debug Console (Right-click and select "Copy All").
          render: shell
      validations:
          required: true
